ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_role TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_label TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS meta JSONB;
